### ISSUE TITLE
可否主動發訊息提醒顧客有即將到來的預約

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#11]
目前草案：提醒最多三次，以小時為單位，也就是幾小時前提醒

**Comment by zhis-rita** [comment]
### 實做提醒機制mis2 api端

1. 提醒資料存放位置，先確定linkrequest不合用再開新table
2. 「幾小時前提醒」設定值，儲存在BookingAppSetting，Shop資料表可覆寫 (設定畫面別題處理)
3. 當預約資料 新增/修改/刪除 時，修改對應的crm資料，並等鬧鐘程式api確定後同步更改鬧鐘設定
4. 鬧鐘的callback api，這是一個不用登入的api，但也要能給出正確的crm資料主鍵才能運行。基本上要做的事就是發推播、寫log，不用再次檢查時間。
5. mis2有時區問題，請小心

**Comment by zhis-rita** [comment]
### 實做提醒時間設定畫面

> 先做BookingAppSetting的部分就好，店家覆寫以後再一起處理。
> 與其他預約設定擺在一起就好，怎麼排版我們再討論~

**Comment by zhis-rita** [comment]
### 沒有參考到shop.bra設定、提醒時間如果重覆應該要擋下來

> 1. 會參考到[shop].[bra]的提醒時間，如果[shop].[bra] 為null值則以[bookingappsetting].[bra]為主
> (程式判斷會參考[shop].[bra]，但目前並未實作[shop].[bra]的設定頁面)
> 2. 如果設定的提醒時間有重複，不會重複提醒。
> 範例:[bookingappsetting].[bra] 設定 1,2,1 ，則同一筆預約在前一個小時還是只會提醒一次
> 3. .預約時間只能設定為大於等於0的數字，可接受小數 ex.0.25

**Comment by zhis-rita** [comment]
以上問題已修正

By Dylan

**Comment by zhis-rita** [comment]
7/12測試功能正常

By Molly

**Comment by zhis-rita** [comment]
已上共用測站

By Dylan

**Comment by zhis-molly** [comment]
測試OK
