### ISSUE TITLE
使用秘密頁面(編輯付款方式)要刪除沒有使用過的付款方式無法移除

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#15]
秘密頁面-編輯付款方式 http://mis2.zhis.com/payment.html
使用此頁面要刪除沒有使用過的付款方式，系統會跳出錯誤訊息`該付款方式目前有被使用 `
如果要刪除的付款方式有同名情況(receive=True、receive=False) 且 另一個同名付款方式有被使用過，會產生誤判情況!

ex.要刪除`receive=True、name=支票`，但因為`receive=False、name=支票` 有被使用過，會導致無法成功刪除~

**Comment by zhis-dora** [comment]
測試OK
