### ISSUE TITLE
登出時刪除的session要複製到logouts資料表，lastaccesstime改放登出時間

### ISSUE THREAD

**Issue by zhis-dylan** [zhis/tr#159]
已新增`logouts`資料表，該表schema與`sessions`完全一樣；
登出的session會被刪除，但現在要在刪除前將資料複製到`logouts`資料表，只有`lastaccesstime`要變更成此時此刻(登出的時間)。

我不太記得`lastaccesstime`會不會考慮company timezone，請先確認此點後，決定要寫入`logouts.lastaccesstime`的時區是什麼。

**Comment by zhis-jason** [comment]
`mis1-app` 與 `mis1-ieonly` 有在本機端測試可以寫入 `logouts` 並刪除。
但是 mis2 連接的資料庫為正式端，所以沒有確定是否有寫入。

**Comment by zhis-dylan** [comment]
訓練組測試時，只要能正常登入登出不回出錯即可算pass

**Comment by zhis-dora** [comment]
測試OK
