### ISSUE TITLE
帳密錯誤的提示訊息白話點

### ISSUE THREAD

**Issue by zhis-dylan** [zhis/tr#189]
![image (34)](https://user-images.githubusercontent.com/82086338/132312282-5bba4d0d-5ec9-4023-90fb-c62b40c6bee7.png)

clickup: `PASS`
creat by Dora

**Comment by zhis-dylan** [comment]
判斷錯誤訊息包含字串 account or password invalid 時，就把整個錯誤訊息改成 帳號或密碼錯誤

by Dylan

**Comment by zhis-dylan** [comment]
輸入正確帳密馬上就可登入，若輸錯帳密會轉圈圈轉很久然後跳出該訊息，請協助，感恩。
![image (35)](https://user-images.githubusercontent.com/82086338/132317220-b5309494-9e54-4393-b073-a280372aca0b.png)

by Dora

**Comment by zhis-dylan** [comment]
問題已修正

by Dylan

**Comment by zhis-dora** [comment]
請問是直接在 https://sms.zhis.com/login.jsp 測試嗎?

**Comment by zhis-dylan** [comment]
是的，看起來已經上正式很久。測試ok
