### ISSUE TITLE
mlis客戶名稱或狀態有特殊符號導致不能驗證

### ISSUE THREAD

**Issue by zhis-dora** [zhis/tr#194]

**Comment by zhis-irene** [comment]
目前使用Kevin的官方帳號預約
如果Line名稱、備註有打了 空白 間隔
在mis2 上的顯示都會變+號
但在預約時的備註，空白就有正常呈現，沒有辦轉換成+號

![image](https://user-images.githubusercontent.com/87798762/133203200-f9fdcdad-118a-4710-996f-e994132ec2ef.png)

**Comment by zhis-kevin** [comment]
此問題經討論及測試後，可能問題在line多編碼了一次，導致解碼造成不同的結果。
尚未修正完成！

**Comment by zhis-kevin** [comment]
此問題已修正編碼問題，可以於kevin生活圈進行測試~

**Comment by zhis-dylan** [comment]
這一題現在不更新就要等連假後，所以還沒pass就先上正式平台了！
