### ISSUE TITLE
點選右上角帳號資訊的「change password」連回MIS1首頁時會跳出錯誤訊息「Object required」

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#33]
![image (19)](https://user-images.githubusercontent.com/54170793/126744711-42604cd6-fdf4-4962-a062-91c8ad27a56c.png)

**Comment by zhis-rita** [comment]
連帶上方的my profile也有相同問題，
經查後發現這兩個連結都是MIS1的.asp頁面，
改為.aspx後my profile正常運作，但change password無法，
發現原因是MIS1開啟userpasswordchange.aspx頁面，
是透過POST表單開啟，並傳送USERID進去才抓地到資料，
所以無法直接透過連結打開頁面，
還要常是新增類似的動作到MIS2

By Ryan

**Comment by zhis-jason** [comment]
修改為 .aspx 檔案，`userpasswordchange.aspx` 頁面因為需要用到 USERID，當參數，所以修改為 GET 用網址傳送。
`window.open(`//${ zhis.mis.server.env.MIS1_APP_HOST }/userpasswordchange.aspx?id=${zhis.mis.secure.me.id}`, '_blank');`

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK
