### ISSUE TITLE
當日營業資訊付款金額有誤

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#35]
![image (22)](https://user-images.githubusercontent.com/54170793/126746645-a200b06c-b910-4371-be69-e3823fb25e0c.png)

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-molly** [comment]
在pub旗艦店7/26 輸入2張測試帳單，
付款方式「信用卡2」同時有未選擇與有選擇信用卡種情況，當日營業資訊會變成Runtime Error

```
付款方式「信用卡2」 
未選擇信用卡種 合計金額300
選擇信用卡種「刷卡-A」合計金額250
```

**Comment by zhis-rita** [comment]
> 在pub旗艦店7/26 輸入2張測試帳單，
> 付款方式「信用卡2」同時有未選擇與有選擇信用卡種情況，當日營業資訊會變成Runtime Error
> 
> ```
> 付款方式「信用卡2」 
> 未選擇信用卡種 合計金額300
> 選擇信用卡種「刷卡-A」合計金額250
> ```

目前已修改，已能正常顯示。

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK
