### ISSUE TITLE
跨平台輸入其他店家進貨交易並選擇月結付款，跳出的對象店家銷貨付款方式會異常

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#37]
範例:
在旗艦店輸入向其他分店進貨交易，店家選擇公益店並選擇月結付款。
系統對應跳出的公益店銷貨給店家紀錄的付款方式應該要呈現「使用賒帳付款」，但卻呈現「使用進階付款方式...」
點選OK後會跳出錯誤訊息「找不到物件」
![image (16)](https://user-images.githubusercontent.com/54170793/126753609-c4ab3c89-e606-4e40-a780-9b9a459ac247.png)
![image (17)](https://user-images.githubusercontent.com/54170793/126753618-77e846d8-66d0-46bc-9cee-5410588dd6a5.png)

**Comment by zhis-irene** [comment]
測試OK~

**Comment by zhis-dora** [comment]
付款方式除了[使用月結付款]外，其餘付款方式一樣有原本的問題

**Comment by zhis-rita** [comment]
> 付款方式除了[使用月結付款]外，其餘付款方式一樣有原本的問題

現金測試是沒有問題的
而其餘跳進階的原因是因為名稱未有對應的付款方式
![image](https://user-images.githubusercontent.com/54170793/128680558-f832cf30-f2be-4d09-8194-5b27501e433f.png)
![image](https://user-images.githubusercontent.com/54170793/128680674-3dc353bd-89a3-4598-9c01-32abb49d7633.png)

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-vicky** [comment]
測試OK
