### ISSUE TITLE
MIS1儀錶板參數[只有特定的業績列入表內?] ，下方手動新增業績選項增加可以指定該業績type功能

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#44]
手動新增業績選項的條件，要修改為 `featname:報表呈現名稱:type`
都使用:隔開設定，第一個參數 代表要抓取的featname、第二個參數 代表報表顯示名稱、第三個參數代表 要抓取的type,如果無指定代表不過濾type
ex.
` v:技術業績:16` ，代表抓featname='v' and type=16，在報表呈現名稱為 技術業績
`v:虛業績` ，代表抓featname='v'，在報表呈現名稱為 虛業績

**Comment by zhis-irene** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-vicky** [comment]
測試OK
