### ISSUE TITLE
新增函式讓訓練師撰寫儀錶板時可以解析JSON資訊

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#45]
目前記錄交易延伸資訊是使用JSON模式，如果用戶需要自訂儀表板分析延伸資訊很難解析。

**Comment by zhis-rita** [comment]
如果要解析transaction.extif欄位的json資料，
 SQL部分 只要正常撈出該欄位即可，
where條件要下extif is not null and extif <> ''，過濾沒有的資料；
 script列出欄位的部分，
則必須要依序列出序號、項目、內容三個欄位，方可解析
<column arg0="序號" dt="string" />
<column arg0="項目" dt="string" />
<column arg0="內容" dt="string" />

呈現結果如下圖：
![001 (1)](https://user-images.githubusercontent.com/54170793/126756166-f596e2ae-bb6b-4ac2-beb1-df38ad7067a0.PNG)
![002 (2)](https://user-images.githubusercontent.com/54170793/126756180-a59e6521-526b-4b09-ae09-352106706287.PNG)

**Comment by zhis-irene** [comment]
請問可否針對extif中序號、項目、內容的欄位，進行語法的篩選

例如：
看有填寫內容的`(SQL: 內容 is not null)`
項目為時間的`(SQL: 項目 Like '%時間%'  or 項目='時間')`

目前測試好像寫死的，只能全撈，無法篩選
![image](https://user-images.githubusercontent.com/87798762/127955471-5195ae69-59fb-4d55-9d0a-bc7aa33ed4c8.png)

**Comment by zhis-dora** [comment]
無法join到其他資料表抓取其他欄位

**Comment by zhis-rita** [comment]
研究如何調整，當初沒有考慮到撈取其他表以及欄位，也沒想過有進階搜尋的概念

**Comment by zhis-rita** [comment]
> 請問可否針對extif中序號、項目、內容的欄位，進行語法的篩選
> 
> 例如：
> 看有填寫內容的`(SQL: 內容 is not null)`
> 項目為時間的`(SQL: 項目 Like '%時間%' or 項目='時間')`
> 
> 目前測試好像寫死的，只能全撈，無法篩選
> ![image](https://user-images.githubusercontent.com/87798762/127955471-5195ae69-59fb-4d55-9d0a-bc7aa33ed4c8.png)

**Comment by zhis-rita** [comment]
> 請問可否針對extif中序號、項目、內容的欄位，進行語法的篩選
> 
> 例如：
> 看有填寫內容的`(SQL: 內容 is not null)`
> 項目為時間的`(SQL: 項目 Like '%時間%' or 項目='時間')`
> 
> 目前測試好像寫死的，只能全撈，無法篩選
> ![image](https://user-images.githubusercontent.com/87798762/127955471-5195ae69-59fb-4d55-9d0a-bc7aa33ed4c8.png)

SQL沒法這樣進階撈是正常的
整個的寫法是SQL撈出來後，才在程式碼進行解析，SQL自然是撈不到所謂`項目`的欄位
如果要篩選的話，可能要寫在`<column arg0="項目" dt="string" />`裡面
我再看看可以怎麼改

**Comment by zhis-rita** [comment]
> 無法join到其他資料表抓取其他欄位

這部分經過測試後，並不是`當初沒有考慮到撈取其他表以及欄位`的原因
而是沒考慮到有`<column arg0="姓名" arg1="CID" dt="string" format="&lt;a href='customerdetail.aspx?id={1}' target='_new'&gt;{0}&lt;/a&gt;" />`這種寫法的緣故
增加判斷後即可撈取其他欄位。

**Comment by zhis-dora** [comment]
> 無法join到其他資料表抓取其他欄位
測試OK

**Comment by zhis-rita** [comment]
研究如何進階篩選json資料，
目前想法為`若要篩選條件，於要篩選的欄位添加json屬性，填入like '日期'或='日期'之類的條件，再於要列出表的地方判斷是否列出(未完成)`

**Comment by zhis-rita** [comment]
- 目前SQL server已經更新2019版本了，可以使用SQL原生的解析json語法

-->`JSON_VALUE` : 這個語法需要指定$[0].name、$[1].name、...這種方式，但通常一筆json不只一個物件(圖一)
-->`OPENJSON` : 可一次解析一筆json，但不確定能不能解析多筆資料的json，SQL server 的 `database compatibility level` 需130以上

- 研究如何使用OPENJSON、使撈出的每筆資料的json都能被解析以及如何對撈出的json添加序號

![image (16)](https://user-images.githubusercontent.com/54170793/128494211-ae2ff139-be82-49ce-b2de-e1b03aa06005.png)
![image (17)](https://user-images.githubusercontent.com/54170793/128494276-2b4a3fae-cfeb-4ab1-a462-b7f550c54367.png)

**Comment by zhis-mandy** [comment]
OPENJSON 測試OK

**Comment by zhis-rita** [comment]
```
SELECT 
    id AS ID,item_categoryname AS 類別,jtable.項目,jtable.內容
FROM [Transaction] [t]
CROSS APPLY OPENJSON (extif)
WITH (
    項目 NVARCHAR(200) '$.name',  
    內容 NVARCHAR(200) '$.value'
) AS jtable
where extif <> ''
```
這種寫法能夠解析多筆的json，也可以下where條件進行篩選
![image](https://user-images.githubusercontent.com/54170793/128680201-868a5b70-c5bf-42b3-9e7b-cd258486c26b.png)

**Comment by zhis-dylan** [comment]
這一題儀表板本身不做修改，請改用OPENJSON達成~
