### ISSUE TITLE
帳單備註開始讓使用者填寫

### ISSUE THREAD

**Issue by zhis-dora** [zhis/tr#54]
網頁顯示比例較大的時候，經辦人會看不到，下圖為175%
![image](https://user-images.githubusercontent.com/87798848/128309946-b74d9384-202c-47cb-85f3-c6feaf61c565.png)

**Comment by zhis-jason** [comment]
這部分因為分成左邊的經辦人跟右邊的指定部分，
如果左邊要放大相對右邊就會縮小，會壓縮到右邊的顯示部分。
所以能調整的幅度可能有限。
請問這部分有想要如何調整嗎?
圖片為右半部分縮短間距後的樣子
原本:
![image](https://user-images.githubusercontent.com/82086338/128315806-26f9c0a5-d5f3-4a95-a7ac-98bd6ec8c7a9.png)
調整:
![image](https://user-images.githubusercontent.com/82086338/128315179-ee84fa69-0c5d-48b9-b846-71de03ca4e1d.png)

**Comment by zhis-molly** [comment]
有可能把「來店日期」、「客戶」、「經辦人」三個區塊的間隔調近一些，省下來的空間移給「經辦人區塊使用」嗎?

![image](https://user-images.githubusercontent.com/87799016/128321034-6ea0751e-0aff-4a3c-94dc-f5ca0e276829.png)

**Comment by zhis-jason** [comment]
將欄位改成這樣可以嗎?
![image](https://user-images.githubusercontent.com/82086338/128329242-d468b398-ddd7-41ee-b2ea-9647426d3d48.png)

**Comment by zhis-molly** [comment]
為了讓175%的可以看到完整的經辦人名稱，反而造成100%的畫面看起來有點極端...
有辦法找出還沒有加上帳單備註的「經辦人下拉選單」寬度，讓現在的選單寬度跟以前一樣就好嗎?

**Comment by zhis-jason** [comment]
不知道這樣的留白會不會很奇怪，但是這跟螢幕的大小有關係。
100%
![image](https://user-images.githubusercontent.com/82086338/128467937-65b9c4c2-85e4-44b4-9aa0-a4cd4d7f6a15.png)
175%
![image](https://user-images.githubusercontent.com/82086338/128467982-faf77a37-6c49-435e-98f3-e4b698c0894b.png)

**Comment by zhis-jason** [comment]
[cross測試站](https://mis1.jason.zart.dev/) 已可以測試

**Comment by zhis-molly** [comment]
跨平台個人測站部分測試OK

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-jason** [comment]
目前因為 IE 無法使用 `min-width` 來設定最小寬度，
找尋代替方案太過麻煩，所以討論過後決定，
隱藏 IE 的備註欄位，不開放 IE 使用備註功能。
並將頁面顯示回原本的樣式。

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-vicky** [comment]
測試OK
