### ISSUE TITLE
IE-only使用JS拆帳存單，跳出的錯誤訊息會變成一堆問號

### ISSUE THREAD

**Issue by zhis-molly** [zhis/tr#55]
![image](https://user-images.githubusercontent.com/87799016/128677922-808a0db6-aeca-4288-abfc-d1ec8fc94464.png)
![image](https://user-images.githubusercontent.com/87799016/128677935-47ea54c4-f6e7-464c-8d1b-2f1483802be3.png)

**Comment by zhis-molly** [comment]
![image](https://user-images.githubusercontent.com/87799016/128677713-264b3a7e-5cd3-487a-8ef6-c2e3b3467120.png)
![image](https://user-images.githubusercontent.com/87799016/128677887-45217b6c-c045-4d14-b797-b62b7c9ede83.png)

**Comment by zhis-jason** [comment]
問題還在處理中，原因目前來沒辦法確定。
不確定 IE 是否支援 JSON 格式的回傳。
[筆記](https://wistful-stock-520.notion.site/IE-only-JS-55-eb5745fb3ed24772af962fd28289775b)

**Comment by zhis-jason** [comment]
目前問題為 API 回傳的 status 不相同。
在 cross 會是 success 但是在 IE 為 error
所以在回傳上會不相同。造成回傳的結果同。
但 error 中的中文字，不論是哪邊都試顯示 `????` 可能是編碼問題。
![image](https://user-images.githubusercontent.com/82086338/130205858-84aee9c0-7a93-4677-9991-cba465e70485.png)

**Comment by zhis-jason** [comment]
目前修改了 `ReplaceServlet.java` 中的 response 編碼。
`jspai.js` 的response中文已經可以正常顯示。

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK
