### ISSUE TITLE
預約表在拒絕Mlis預約的拒絕原因或改約建議這邊讓用戶可以自訂常用回覆訊息

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#6]
![image (18)](https://user-images.githubusercontent.com/54170793/126606796-55ca244f-38ae-488e-bce3-e67ec652bb8b.png)

**Comment by zhis-rita** [comment]
以下幾點需要修改~

1.儲存常用原因的說明字樣修改為「儲存為常用拒絕原因(上限20筆)」

2.如果將儲存訊息的按鈕打開但沒有輸入任何原因，會跳出無法插入null值到資料行的錯誤訊息

> 此情況應該要自動忽略，不需更新常用拒絕原因

3.登入帳號如果沒有預約記錄的寫入權，點選接受按鈕畫面會卡住不動(應該要跳出權限不足的錯誤訊息)

4.儲存常用拒絕原因應該要參考預約記錄的寫入權

> 目前點選拒絕並打開儲存訊息的按鈕會跳出權限不足的錯誤訊息，但常用拒絕原因卻會寫入系統

by Molly

**Comment by zhis-jason** [comment]
目前增加權限判斷，阻止無權限的操作。

但因每次都有權限判斷，造成回傳的`權限不足`視窗跳出多次。
思考有沒有辦法修改執行順序減少視窗的彈出。

**Comment by zhis-molly** [comment]
1.預約記錄寫入權參考不完整

> 帳號擁有`預約記錄全域讀取權` 與 `公益店預約記錄寫入權`，在公益店的行為正常。
但在旗艦店點選拒絕會跳出權限不足的錯誤訊息，但常用拒絕原因還是會寫入系統!

2.拒絕預約並儲存了新常用拒絕原因後，畫面會跳轉到MIS2首頁，應該要停留在預約表頁面

**Comment by zhis-jason** [comment]
第一點已做修改，增加店家個別權限判斷，而非單純判斷權限。
第二點目前拿掉重新整理的部分，使頁面留在原畫面。
當初會讓他重整的原因是因為新增以後不重整將不會出現新增的選項。
目前是有辦法重整再預約畫面，但日期的部分目前沒有辦法選擇，只能是當天。
需要再找找有沒有辦法調整時間。

**Comment by zhis-jason** [comment]
嘗試過 `zhis.mis.app.open('booking')` 但他似乎只有開啟頁面沒有重整功能，所以無法使用。
網址帶入變數 `?app=booking` 似乎最接近需求，但他只能開啟當天，所以放棄。除非還能帶入日期變數跳轉時間。
目前嘗試使用賴總的方法，`.scroll()` 但還不確定擺放位置，可以放在 selector 上面但是會影響太多同樣使用該選擇器的部分。
所以還在嘗試，或是使用 `refresh` 更新選項。

修改 `switch` 開關，放大按鈕使之可以在平板上面順利點擊。
![image](https://user-images.githubusercontent.com/82086338/127304250-b3cffbe8-ce4f-457c-aa72-ab16cc99dba8.png)

**Comment by zhis-jason** [comment]
修改按鈕間距
![image](https://user-images.githubusercontent.com/82086338/127472174-6392f414-4d71-495a-b0cd-2f8d2e387dcb.png)

嘗試使用 refresh 按鈕，點擊以後會重新載入參數 map 的值，思考如何修改參數 map。
新增後使用 `new zhis.mis.selector.Map(rejectmessage)` 雖然會得到新的 map 參數，但不會寫入原本的部分。

**Comment by zhis-dora** [comment]
![image](https://user-images.githubusercontent.com/87798848/127606635-b8ed1066-72ba-4e44-b96c-fd8e665c3ba8.png)
接受預約的視窗，不應該出現「儲存為常用拒絕原因(上限20筆)」

**Comment by zhis-dylan** [comment]
> 嘗試過 `zhis.mis.app.open('booking')` 但他似乎只有開啟頁面沒有重整功能，所以無法使用。
> 網址帶入變數 `?app=booking` 似乎最接近需求，但他只能開啟當天，所以放棄。除非還能帶入日期變數跳轉時間。
> 目前嘗試使用賴總的方法，`.scroll()` 但還不確定擺放位置，可以放在 selector 上面但是會影響太多同樣使用該選擇器的部分。
> 所以還在嘗試，或是使用 `refresh` 更新選項。
程式碼的苦惱留在PR那邊比較適當，這裏還是以能跟訓練組討論的為主XD
 
> 修改 `switch` 開關，放大按鈕使之可以在平板上面順利點擊。
這一句就適合放這邊~

**Comment by zhis-jason** [comment]
修改文字顯示條件
新增按鈕，讓新增的`拒絕訊息`顯示時不用網頁重整。
![image](https://user-images.githubusercontent.com/82086338/127818288-a17e9460-aa57-4691-9c75-696c5139dccb.png)

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-molly** [comment]
新增了常用拒絕原因後，點選右上角重整按鈕還是沒有出現新增的常用訊息。

**Comment by zhis-jason** [comment]
改寫程式碼

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-dora** [comment]
打開儲存訊息的按鈕，但沒有輸入原因，會跳出「無法插入 NULL 值到資料行 'name'，資料表 'mis_Pub.dbo.Setting'; 資料行不得有 Null。INSERT 失敗。」的錯誤訊息

**Comment by zhis-dylan** [comment]
在RC問題的處理方式請參閱https://github.com/zhis/tr#rc，除了加上`needfix`外還要Reopen issue！

**Comment by zhis-dora** [comment]
好的

**Comment by zhis-jason** [comment]
新增內容判斷，如果為空值將不執行 API 動作。

已重新放上[我的測試站](https://mis2.jason.zart.dev/index.html?hl=zh_TW_salon)

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-dylan** [comment]
請協助測試，如果內容為一或多個空白字元，會出錯嗎？
遇到單純空白字元的內容時該如何處理較合理？照樣存起來？

**Comment by zhis-jason** [comment]
這部分因為有使用 `trim()` ，所以他會變成空字串，如果空字串值會存成 `null` 。

**Comment by zhis-dora** [comment]
之前測試時，有打過一個空格，他會當成沒有輸入內容處理

**Comment by zhis-dylan** [comment]
ok, 那這樣無論是空字串或幾個空白都不存，沒有問題~

**Comment by zhis-dora** [comment]
測試OK
