### ISSUE TITLE
pub資料庫，舊帳單呈現的交易順序異常

### ISSUE THREAD

**Issue by zhis-molly** [zhis/tr#65]
正式站查看舊帳單，MIS1與MIS2呈現的交易順序是不一樣的，
MIS1呈現的順序有依照[transaction].[sortindex]，但MIS2沒有。
目前只有pub資料庫會有此情況，不確定跟pub資料庫有升級相容性層級有無相關
![image](https://user-images.githubusercontent.com/87799016/130033967-e132ec0c-53ce-49a8-bf95-b4bbe6949f79.png)

**Comment by zhis-rita** [comment]
這部分修改兩個地方
1. 一張帳單的交易順序部分
2. 左邊帳單列表的排序

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK
