### ISSUE TITLE
pub資料庫，使用小票列印呈現的數據異常

### ISSUE THREAD

**Issue by zhis-molly** [zhis/tr#66]
帳單使用計次券付款呈現的金額異常、交易呈現順序也與帳單不同。
目前只有pub資料庫會有此情況，不確定跟pub資料庫有升級相容性層級有無相關

![image](https://user-images.githubusercontent.com/87799016/130575824-371abfab-0f90-4f68-b585-2de3d4e66fa9.png)
![image](https://user-images.githubusercontent.com/87799016/130575835-e9bcd24f-c4fb-4abc-b436-5c95673acadb.png)

**Comment by zhis-rita** [comment]
這部分修改三個地方
1. wsm2002標準樣式(卡券)
2. 57mm紙卷樣式
3. 76mm紙卷樣式

第1點的部分應該是本來就沒有問題，
但寫法都是將資料INTO進去虛擬表，
之後撈虛擬表的時候沒有給ORDER BY，
所以還是改了

**Comment by zhis-ada** [comment]
測試OK

**Comment by zhis-molly** [comment]
MIS1跨平台與MIS2部分測試OK

但使用IE開啟MIS1或MIS2都無法列印帳單，MIS1會跳出錯誤訊息「SecurityError」、MIS2則跳出「列印時發生錯誤」
共用測站(mis.zart.dev)也會有此問題

**Comment by zhis-rita** [comment]
目前查找不出確切原因，因此問題與order by無關聯，
故另開題，之後再查詢
(正式平台目前沒有問題)

**Comment by zhis-dora** [comment]
測試OK
