### ISSUE TITLE
【帳單列印】可以選擇是否印出項目的原價、折讓金額、指定設計師

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#7]
用戶希望小票列印出來
可以顯示原價(price)與折讓金額(discount) ，非先前的顯示備註欄
因小票的寬度有限，不好擠那麼多字

需異動範圍如下
1.新增列印參數「+p」，如有設定此參數就多呈現原價.折扣.總計資訊
2.下方經辦人後方多呈現指定.不指定資訊 (不需參數設定，直接顯示出來)
3.經辦人改抓[employee].[vipname]，如果沒有vipname才改抓name
![image (20)](https://user-images.githubusercontent.com/54170793/126610472-ffc74505-b766-4560-bf3b-8505f2333dc3.png)

**Comment by zhis-rita** [comment]
調整此題異動內容
1.新增列印參數「+p」，如有設定此參數就多呈現原價.折扣.總計資訊
2.是否指定經辦人部分不需要參數，直接顯示出來就好
3.移除顯示客戶行動電話的功能(因為客戶機密權會限制不可查看行動電話，避免衝突)
![image (21)](https://user-images.githubusercontent.com/54170793/126610650-f77551c6-9c2c-4d0e-af1e-9e7b39aff538.png)

**Comment by zhis-rita** [comment]
新增列印參數「+p」、經辦人呈現指定.不指定、經辦人改抓vipname部分測試OK
但如果帳單經辦人空白沒有填，存單畫面會卡住且不會送出列印資訊!

by Molly

**Comment by zhis-jason** [comment]
已修改經辦人空白無法列印問題，經辦人未填將以空白顯示。

**Comment by zhis-dora** [comment]
測試OK

**Comment by zhis-molly** [comment]
測試OK

**Comment by zhis-vicky** [comment]
測試OK

**Comment by zhis-dora** [comment]
測試OK
