### ISSUE TITLE
預付卡券有登打到對象非客戶的交易時，該卡號儲值帳戶明細頁面會無法顯示

### ISSUE THREAD

**Issue by zhis-rita** [zhis/tr#8]
如果預付卡券有透過交易列表"分項"功能輸入對象非客戶的抵用紀錄，
該卡號在MIS2的儲值帳戶明細會無法顯示，並跳出錯誤訊息[從字元字串轉換到uniqueidentifier時失敗。]
(在MIS1的儲值帳戶明細頁面可以正常顯示)

ex：
2021/5/12旗艦店銷貨至高雄店交易，付款方式使用分項(儲值卡3000 - S20210507001)付款
此卡號S20210507001 在MIS2儲值帳戶明細頁面無法顯示

MLIS有類似的問題，同一筆交易造成mlis在查詢使用紀錄時發生錯誤：
![image (22)](https://user-images.githubusercontent.com/54170793/126610884-39dafc1b-018c-432e-b649-e5b224c9b153.png)

**Comment by zhis-molly** [comment]
MIS2卡券詳細資料部分，目前正式站是正常的
MLIS卡券餘額部分測試OK

**Comment by zhis-dora** [comment]
mis2正式站無此問題，mlis測試OK

**Comment by zhis-vicky** [comment]
mis2正式站正常，mlis測試OK

**Comment by zhis-dora** [comment]
測試OK
